/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as JobsIndexImport } from './routes/jobs/index'
import { Route as JobsAddImport } from './routes/jobs/add'
import { Route as JobsIdsImport } from './routes/jobs/$ids'

// Create Virtual Routes

const AddJobLazyImport = createFileRoute('/add-job')()

// Create/Update Routes

const AddJobLazyRoute = AddJobLazyImport.update({
  path: '/add-job',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add-job.lazy').then((d) => d.Route))

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const JobsIndexRoute = JobsIndexImport.update({
  path: '/jobs/',
  getParentRoute: () => rootRoute,
} as any)

const JobsAddRoute = JobsAddImport.update({
  path: '/jobs/add',
  getParentRoute: () => rootRoute,
} as any)

const JobsIdsRoute = JobsIdsImport.update({
  path: '/jobs/$ids',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/add-job': {
      preLoaderRoute: typeof AddJobLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/$ids': {
      preLoaderRoute: typeof JobsIdsImport
      parentRoute: typeof rootRoute
    }
    '/jobs/add': {
      preLoaderRoute: typeof JobsAddImport
      parentRoute: typeof rootRoute
    }
    '/jobs/': {
      preLoaderRoute: typeof JobsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  AddJobLazyRoute,
  JobsIdsRoute,
  JobsAddRoute,
  JobsIndexRoute,
])

/* prettier-ignore-end */
